site_name: Guia de Estilo para Traduções e Transcrições em Português (Brasil) no TED Translators
nav:
    - Início: 'index.md'
    - Sobre: 'sobre.md'
    - Guia:
        - 'Transcrições': 'transcricoes.md'
        - 'Números e Numerais': 'numeros_numerais.md'
        - 'Unidades de Medida': 'unidades_medida.md'
        - 'Uso das Aspas no Discurso Direto': 'aspas_direto.md'
        - 'Citações e trechos de obras literárias': 'citacoes.md'
        - 'Termos Estrangeiros': 'termos_estrangeiros.md'
        - 'Sons': 'sons.md'
        - 'Mudança de idioma durante a palestra': 'mudanca_idioma.md'
        - 'Entrevistas e múltiplos locutores': 'entrevistas.md'
        - 'Quebras de Linha': 'quebras.md'
        - 'Sincronia': 'sincronia.md'
        - 'TEDx': 'tedx.md'
        - 'Prefixos, Uso do Hífen e o Acordo Ortográfico Vigente': 'acordo.md'
        - 'Onomatopeias': 'onomatopeias.md'
        - 'Equívocos Frequentes': 'equivocos.md'
        - 'Glossário': 'glossario.md'
        - 'Ferramentas Úteis': 'ferramentas.md'
theme: readthedocs
google_analytics: ['UA-45971598-3', 'auto']
